code_review:
  disable: false
  comment_severity_threshold: LOW
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: true
    code_review: true
  pull_request_review_comment:
    help: false
    summary: false
    code_review: true
  path_filters:
    - "!**/*.md"

have_fun: false
